name: multi_file_demo

inputs:
  source__records:
    uri: records/*.csv
    combine_strategy: concat

steps:
  - id: double_amount
    uses: steps.normalize.double_amount
    with:
      records: source__records
      normalized: records_norm

outputs:
  datasets:
    - name: final
      from: records_norm
